### ISSUE TITLE
Update game physics for gameplay

### ISSUE THREAD

**Issue by jgionti** [clt313/SuperballVR#26]
- Make sure ball collision works against everything
- Give the ball volleyball gravity (a little lighter than it is right now)
- Add a forgiveness hitbox surrounding the hands to make hitting the ball easier

**Comment by haroonsyed** [comment]
Rigidbodies are added, but the ball's speed after being hit isn't correct.

**Comment by haroonsyed** [comment]
Currnet issues:

1. I found the XRRig is colliding with ball and is detected as OOB (since only hands are recognized as part of object)
2. Spawn position of ball needs to be relative to main camera, not XR rig since that's touching ground.
    This also requires udpating the tests to have a main camera object.

**Comment by jgionti** [comment]
Resolved by #44.
