### ISSUE TITLE
Create persistent storage for settings menu

### ISSUE THREAD

**Issue by jgionti** [clt313/SuperballVR#4]
From the settings menu, be able to load from and write to a file for each of the settings.

We can keep it easy to read, like a settings.json maybe?

## Tasks
- [x] Add read/write functionality for settings file
- [x] Integrate with settings menu

**Comment by jgionti** [comment]
Started the settings script in the [settings branch](https://github.com/clt313/SuperballVR/tree/settings). Apparently, Unity has a built-in way of storing simple data between sessions: https://docs.unity3d.com/ScriptReference/PlayerPrefs.html

On Windows, the preferences are located in the Computer\HKEY_CURRENT_USER\SOFTWARE\Unity\UnityEditor\DefaultCompany\SuperballVR registry (Win+R "regedit" to view the registry editor).

**Comment by FSanchez-UF** [comment]
Persistent storage for volume levels and graphic options in the settings menu was achieved. The music and sound volume are also scaled to master volume. Script for storage and volume scaling are in SettingsMenu.cs
