### ISSUE TITLE
Add a script to assist with hitting the ball

### ISSUE THREAD

**Issue by jgionti** [clt313/SuperballVR#89]
As we all know, hitting the ball can be janky. We need a script to help hit the ball where we'd expect it to go.

First Person Tennis does it well: https://youtu.be/xCIwD4gYUcc?t=202 and https://youtu.be/MhY3gOnuPq0
Another potentially helpful physics video: https://youtu.be/j19QDOn2cCc

**Comment by haroonsyed** [comment]
Mostly working now, two improvements can be done still
1. Momentum is not conserved, so hitting a ball slowly, even if it is coming at you fast means it will move slowly
2. Sample hand velocity over multiple frames instead of one, possibly with decreasing weights
